"""initial_schema

Revision ID: d5f5bd821dff
Revises: 
Create Date: 2026-02-27 12:29:23.570523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f5bd821dff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_records_bak')
    op.alter_column('activity_records', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'years_exp',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('candidates', 'starred',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('jobs', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.alter_column('candidates', 'starred',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('candidates', 'years_exp',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('activity_records', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('interview_records_bak',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('link_id', sa.INTEGER(), nullable=False),
    sa.Column('round', sa.VARCHAR(), nullable=True),
    sa.Column('interviewer', sa.VARCHAR(), nullable=True),
    sa.Column('interview_time', sa.VARCHAR(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('conclusion', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'completed'"), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['candidate_job_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
